name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      - name: Create and push tag
        id: create_tag
        run: |
          git tag -a v${{ github.run_number }} -m "Release version v${{ github.run_number }}"
          git push origin v${{ github.run_number }}
